### ISSUE TITLE
Instafeed limit is not working properly

### ISSUE THREAD

**Issue by AngelBS** [stevenschobert/instafeed.js#564] opened 2018-03-08 18:13 UTC
Hi, i'm having an issue since yesterday

```javascript
var userFeed = new Instafeed({
        clientId: '33d81315d7514ccb87f09bbef6397e65',
        accessToken: '1663036935.33d8131.70add55b8acd4528b8ae7ba1bfe58d87',
        get: 'user',
        limit: 10,
        link: 'true',
        userId: '1663036935',
        resolution: 'standard_resolution',
        template: '<div class="instagram-item"><a target="_blank" href="{{link}}"><div class="img-background" style="background-image: url({{image}})"></div></a></div>'
    });
    userFeed.run();
```

I already configured everything, i want to show 5 images on my website, but if i put the limit on 5 it only shows 1 image and if i put the limit on 10 it shows 6, at this moment if i try to increase or decrease the limit it only shows 1 image.

I don't know if it is because of the announcement of the integration with Facebook Graph Api, the limit of requests of the Instagram api or what

**Comment by fersk** [comment] 2018-03-13 20:08
@AngelBS did you manage to sort this? I'm facing the same problem across several sites and Instagram accounts. Instagram API is definitely not sending all pictures.

**Comment by cshold** [comment] 2018-03-15 14:25
Noticed this too, but only for some accounts. Can't figure out what's different about them.

**Comment by fersk** [comment] 2018-03-15 14:29
Yeah, this is only happening for some accounts. I have been trying to figure it out but can't really understand, this definitely seems like something in Instagram API, if you increase the limit you'll eventually get the number you want.

**Comment by cshold** [comment] 2018-03-15 16:44
Can confirm the account I was having the issue on had schedule posts that were hidden, so the arbitrary increase in limit worked.

**Comment by AngelBS** [comment] 2018-03-16 22:54
@fersk i haven't found how to manage this, but as @cshold says it only happens with some accounts, with my account it doesn't happen but with another account it happens and i can't figure out what's going on

But if this is not an issue with instafeed itself we should close this issue

**Comment by benjamin-hull** [comment] 2018-05-15 13:11
Sounds like this is caused by scheduled posts (we should check if they are returned by the API before they're actually published). Closing for now.

**Closed by benjamin-hull** 2018-05-15 13:11 UTC
