### ISSUE TITLE
next() method removed from v2?

### ISSUE THREAD

**Issue by jnicol** [stevenschobert/instafeed.js#647] opened 2020-03-31 06:37 UTC
Hi, I have just tested out Instafeed v2 and it works great! One (undocumented?) difference I have noticed if that the `next` and `hasNext` methods have been removed.

The v1 documentation showed how the `next` method could be bound to a "load more" button to retrieve more images from Instagram. The `hasNext` method could be called in an `after` callback, and if it returned false then the "load more" button would be hidden.

Is their removal an oversight, or are these methods gone for good?

**Comment by stevenschobert** [comment] 2020-03-31 15:43
Hey @jnicol! Great to hear the v2 is working out so far.

Yep, those pagination methods haven't been implemented in the v2 version yet. They're not gone for good though, just haven't quite gotten to that.

Now that the API shutoff deadline has been extended, I think we can get them in before the full v2 launch.

**Comment by jnicol** [comment] 2020-04-01 00:50
Good to hear that Instragram/Facebook has extended the cutoff deadline, and also good to hear that pagination will make it into v2 :)

**Comment by benjamin-hull** [comment] 2020-04-02 09:38
Tracking the reinstatement of these features in #649.

**Comment by stevenschobert** [comment] 2020-07-01 17:49
Closing this issue, since it’s a duplicate of #649

**Closed by stevenschobert** 2020-07-01 17:49 UTC
